### ISSUE TITLE
More eyeballs?

### ISSUE THREAD

**Issue by mjordan** [Islandora/migrate_islandora_csv#3]
@rtilla1 and @rosiel, members of the Metadata IG will be interested in this tutorial. It would be good to get some more eyeballs on it!

**Comment by rosiel** [comment]
Eyeballs engaged! I am in the process (rough) of creating some suggestions, which you can preview here: https://github.com/dannylamb/migrate_islandora_csv/compare/master...rosiel:scratchpad?expand=1 . I want to go revise some of my #fixme's and try to re-create your approachable style. 

Did I get this right that this is a tutorial on using Migrate (i.e. required reading whether you're eventually using CSV or not)?

**Comment by mjordan** [comment]
@rosiel Happy ~eyeballs~ New Year! Depending on when you built your CLAW vagrant, you might need to add `--userid=1` when you run `drush migrate:import` commands. See #4.

**Comment by rosiel** [comment]
Thanks @mjordan! I built it recently, but apparently I didn't update my claw playbook first. Oh geez. 

Ok, a question for you and @dannylamb: can we rename the machine names of the migrations from `file` to something like `islandora_csv_migrate_file` (etc)? It gets confusing trying to tell whether the string file refers to a migration, a column in the CSV, or something internal to Drupal. 
 
```
  # Lookup the migrated file in the file migration.
  field_media_image:
    plugin: migration_lookup
    source: file 
    migration: file 
    no_stub: true

  # Lookup the migrated node in the node migration
  field_media_of:
    plugin: migration_lookup
    source: file 
    migration: node 
    no_stub: true
```
If so, should I make a separate ticket?
